var first = 4;
var second = 5;
console.log(first, second);
var temp;
temp = first;
first = second;
second = temp;
console.log(first, second);
[first, second] = [second, first];
console.log(first, second);
